# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
    labels:
      - "Dependencies"
    open-pull-requests-limit: 10
    reviewers:
      - "ElioDiNino"
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "typescript"