[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload
    '''
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
    default-src  'self';
    script-src   'report-sample' 'self' 'unsafe-inline' https://*.googletagmanager.com https://www.google.com/recaptcha/
                  https://www.gstatic.com/recaptcha/ ajax.cloudflare.com static.cloudflareinsights.com;
    style-src    'report-sample' 'self' 'unsafe-inline' https://*.googletagmanager.com;
    object-src   'none';
    base-uri     'self';
    connect-src  'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com https://*.g.doubleclick.net
                  https://*.google.com https://*.google.ca cloudflareinsights.com *.sentry.io https://api.emailjs.com;
    font-src     'self' data:;
    frame-src    'self' https://td.doubleclick.net https://*.google.com https://app.netlify.com/;
    img-src      'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com https://*.g.doubleclick.net
                  https://*.google.com https://*.google.ca;
    manifest-src 'self';
    media-src    'self';
    worker-src   'self' blob:;
    report-uri   https://o4508218594361344.ingest.us.sentry.io/api/4508495715303424/security/?sentry_key=0656a3ffc6ab7d8195bdf491eea907b3;
    report-to    csp-endpoint
    '''
    Reporting-Endpoints = '''
    csp-endpoint="https://o4508218594361344.ingest.us.sentry.io/api/4508495715303424/security/?sentry_key=0656a3ffc6ab7d8195bdf491eea907b3"
    '''
