[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload
    '''
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
    default-src  'self';
    script-src   'report-sample' 'self' 'unsafe-inline' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/
                  https://ingest.eliodinino.com https://ajax.cloudflare.com https://static.cloudflareinsights.com;
    style-src    'report-sample' 'self' 'unsafe-inline';
    object-src   'none';
    base-uri     'self';
    connect-src  'self' https://api.emailjs.com https://www.google.com/recaptcha/ https://ingest.eliodinino.com https://cloudflareinsights.com https://*.sentry.io;
    font-src     'self' data:;
    frame-src    'self' https://www.google.com/recaptcha/ https://recaptcha.google.com/recaptcha/ https://app.netlify.com/;
    img-src      'self' data:;
    manifest-src 'self';
    media-src    'self';
    worker-src   'self' blob:;
    report-uri   https://o4508218594361344.ingest.us.sentry.io/api/4508495715303424/security/?sentry_key=0656a3ffc6ab7d8195bdf491eea907b3;
    report-to    csp-endpoint
    '''
    Reporting-Endpoints = '''
    csp-endpoint="https://o4508218594361344.ingest.us.sentry.io/api/4508495715303424/security/?sentry_key=0656a3ffc6ab7d8195bdf491eea907b3"
    '''
