[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload
    '''
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
    default-src  'self';
    script-src   'report-sample' 'self' 'unsafe-inline' https://*.googletagmanager.com https://www.google.com/recaptcha/
                  https://www.gstatic.com/recaptcha/ ajax.cloudflare.com static.cloudflareinsights.com;
    style-src    'report-sample' 'self' 'unsafe-inline' https://fonts.googleapis.com;
    object-src   'none';
    base-uri     'self';
    connect-src  'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com https://*.g.doubleclick.net
                  https://*.google.com https://*.google.ca cloudflareinsights.com https://api.emailjs.com;
    font-src     'self' https://fonts.gstatic.com;
    frame-src    'self' https://td.doubleclick.net https://*.google.com https://app.netlify.com/;
    img-src      'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com https://*.g.doubleclick.net
                  https://*.google.com https://*.google.ca;
    manifest-src 'self';
    media-src    'self';
    worker-src   'none'
    '''

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
  # https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Time in seconds to not submit the sitemap after successful submission
	ignorePeriod = 0

	# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
	providers = [
		"google",
		"yandex"
	]

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    skipPatterns = ['https://fonts.gstatic.com', 'https://fonts.googleapis.com']
