[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload
    '''
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
    default-src 'self';
    script-src 'self' 'unsafe-inline' https://www.google.com/recaptcha/api.js https://www.googletagmanager.com/gtag/js https://www.gstatic.com/recaptcha/releases/;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    object-src 'none';
    base-uri 'self';
    connect-src 'self' https://analytics.google.com https://api.emailjs.com https://stats.g.doubleclick.net;
    font-src 'self' https://fonts.gstatic.com;
    frame-src 'self' https://www.google.com;
    img-src 'self' https://www.google.ca;
    manifest-src 'self';
    media-src 'self';
    worker-src 'none'
    '''

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
  # https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Time in seconds to not submit the sitemap after successful submission
	ignorePeriod = 0

	# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
	providers = [
		"google",
		"yandex"
	]
