[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
  # https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Time in seconds to not submit the sitemap after successful submission
	ignorePeriod = 0

	# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
	providers = [
		"google",
		"yandex"
	]
